services:
  front:
    build: ./front
    container_name: front_rio
    ports:
      - "3000:3000"
    depends_on:
      - back
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  back:
    build: ./back
    container_name: back_rio
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:2025@db:5432/db_infra_rio

  db:
    image: postgres
    container_name: db_rio
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 2025
      POSTGRES_DB: db_infra_rio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
