services:
  front:
    build: ./front
    container_name: front_container
    ports:
      - "3000:3000"
    depends_on:
      - back
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  back:
    build: ./back
    container_name: back_container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:2025@db:5432/db_infra_rio

  db:
    image: postgres:lts-alpine
    container_name: db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 2025
      POSTGRES_DB: db_infra_rio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
